import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildMaterialThemeManifests, buildVscodeIconsManifest, ALL_THEME_PACKS } from '../src/icon-engine/manifest-builder';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDir, '..');
const materialIconsSourceDir = resolve(projectRoot, 'node_modules/material-icon-theme/icons');
const iconsTargetDir = resolve(projectRoot, 'public/icons');
const manifestsTargetDir = resolve(projectRoot, 'public/manifests');
const generatedPacksFile = resolve(projectRoot, 'src/generated/theme-packs.ts');
const legacyGeneratedManifestFile = resolve(projectRoot, 'src/generated/material-theme.ts');
const legacyGeneratedPacksFile = resolve(projectRoot, 'src/generated/material-theme-packs.ts');

const vscodeIconsJsonPath = resolve(projectRoot, 'node_modules/vscode-icons-js/data/generated/icons.json');
const iconifyJsonPath = resolve(projectRoot, 'node_modules/@iconify-json/vscode-icons/icons.json');

interface IconifyData {
  prefix: string;
  icons: Record<string, { body: string; width?: number; height?: number }>;
  aliases?: Record<string, { parent: string }>;
  width: number;
  height: number;
}

function buildSvg(body: string, width: number, height: number): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${body}</svg>`;
}

async function extractVscodeIconsSvgs(svgFilenames: string[]): Promise<void> {
  const iconify: IconifyData = JSON.parse(readFileSync(iconifyJsonPath, 'utf-8'));
  const defaultWidth = iconify.width;
  const defaultHeight = iconify.height;

  const writes: Promise<void>[] = [];

  for (const filename of svgFilenames) {
    const iconifyId = filename.replace('.svg', '').replace(/_/g, '-');
    let iconData = iconify.icons[iconifyId];

    if (!iconData && iconify.aliases?.[iconifyId]) {
      const parentId = iconify.aliases[iconifyId].parent;
      iconData = iconify.icons[parentId];
    }

    if (!iconData) {
      continue;
    }

    const width = iconData.width ?? defaultWidth;
    const height = iconData.height ?? defaultHeight;
    const svg = buildSvg(iconData.body, width, height);
    writes.push(writeFile(resolve(iconsTargetDir, filename), svg));
  }

  await Promise.all(writes);
}

async function main() {
  const { manifests: materialManifests } = buildMaterialThemeManifests();
  const { manifest: vscodeIconsManifest, svgFilenames } = buildVscodeIconsManifest(vscodeIconsJsonPath);

  await rm(iconsTargetDir, { force: true, recursive: true });
  await mkdir(iconsTargetDir, { recursive: true });
  await cp(materialIconsSourceDir, iconsTargetDir, { recursive: true });
  await extractVscodeIconsSvgs(svgFilenames);

  await rm(manifestsTargetDir, { force: true, recursive: true });
  await mkdir(manifestsTargetDir, { recursive: true });

  const allManifests: Record<string, unknown> = { ...materialManifests, 'vscode-icons': vscodeIconsManifest };
  await Promise.all(
    Object.entries(allManifests).map(([pack, manifest]) =>
      writeFile(resolve(manifestsTargetDir, `${pack}.json`), JSON.stringify(manifest)),
    ),
  );

  const source = `/* This file is generated by scripts/copy-icons.ts. */
import type { ThemePackId } from '../icon-engine/types';

export const allThemePacks = ${JSON.stringify(ALL_THEME_PACKS, null, 2)} as const satisfies readonly ThemePackId[];
`;

  await mkdir(resolve(projectRoot, 'src/generated'), { recursive: true });
  await writeFile(generatedPacksFile, source);
  await rm(legacyGeneratedManifestFile, { force: true });
  await rm(legacyGeneratedPacksFile, { force: true });
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
