import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildMaterialThemeManifests } from '../src/icon-engine/manifest-builder';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDir, '..');
const iconsSourceDir = resolve(projectRoot, 'node_modules/material-icon-theme/icons');
const iconsTargetDir = resolve(projectRoot, 'public/icons');
const manifestsTargetDir = resolve(projectRoot, 'public/manifests');
const generatedPacksFile = resolve(
  projectRoot,
  'src/generated/material-theme-packs.ts',
);
const legacyGeneratedManifestFile = resolve(
  projectRoot,
  'src/generated/material-theme.ts',
);

async function main() {
  const { manifests, packs } = buildMaterialThemeManifests();

  await rm(iconsTargetDir, { force: true, recursive: true });
  await mkdir(iconsTargetDir, { recursive: true });
  await cp(iconsSourceDir, iconsTargetDir, { recursive: true });

  await rm(manifestsTargetDir, { force: true, recursive: true });
  await mkdir(manifestsTargetDir, { recursive: true });
  await Promise.all(
    Object.entries(manifests).map(([pack, manifest]) =>
      writeFile(
        resolve(manifestsTargetDir, `${pack}.json`),
        JSON.stringify(manifest),
      ),
    ),
  );

  const source = `/* This file is generated by scripts/copy-icons.ts. */
import type { ThemePackId } from '../icon-engine/types';

export const materialThemeIconPacks = ${JSON.stringify(packs, null, 2)} as const satisfies readonly ThemePackId[];
`;

  await mkdir(resolve(projectRoot, 'src/generated'), { recursive: true });
  await writeFile(generatedPacksFile, source);
  await rm(legacyGeneratedManifestFile, { force: true });
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
