import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildMaterialThemeManifests } from '../src/icon-engine/manifest-builder';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDir, '..');
const iconsSourceDir = resolve(projectRoot, 'node_modules/material-icon-theme/icons');
const iconsTargetDir = resolve(projectRoot, 'public/icons');
const generatedFile = resolve(
  projectRoot,
  'src/generated/material-theme.ts',
);

async function main() {
  const { manifests, packs } = buildMaterialThemeManifests();

  await rm(iconsTargetDir, { force: true, recursive: true });
  await mkdir(iconsTargetDir, { recursive: true });
  await cp(iconsSourceDir, iconsTargetDir, { recursive: true });

  const source = `/* This file is generated by scripts/copy-icons.ts. */
import type { Manifest } from 'material-icon-theme';
import type { ThemePackId } from '../icon-engine/types';

export const materialThemeIconPacks = ${JSON.stringify(packs, null, 2)} as const satisfies readonly ThemePackId[];

export const materialThemeManifests = ${JSON.stringify(manifests, null, 2)} satisfies Record<ThemePackId, Manifest>;
`;

  await mkdir(resolve(projectRoot, 'src/generated'), { recursive: true });
  await writeFile(generatedFile, source);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
